### ISSUE TITLE
Uncaught Error: Class 'RoyalMail\.......\LabelsApi' not found

### ISSUE THREAD

**Issue by SithVicious** [zVPS/royal-mail-click-drop-rest-api-client#2]
Can anyone provide some insight into why this would be thrown when using the example code?
I have provided a valid apiKey, and included correct vendor/autoload.php file after composer install.

[Mon Jun  7 23:28:56 2021] ::1:52984 [500]: /integrations/shipping/royalmail/test-clickanddropapi.php - Uncaught Error: Class 'RoyalMail\ClickAndDrop\Rest\Api\RoyalMail\ClickAndDrop\Rest\Api\LabelsApi' not found in C:\Users\PhpstormProjects\web-tools\integrations\shipping\royalmail\test-clickanddropapi.php:9
Stack trace:
#0 {main}
  thrown in C:\Users\PhpstormProjects\web-tools\integrations\shipping\royalmail\test-clickanddropapi.php on line 9

**Comment by Caffe1neAdd1ct** [comment]
Can you provide some sample code to replicate the error please?

Looks like there is most likely an issue with the namespacing being duplicated:

RoyalMail\ClickAndDrop\Rest\Api\RoyalMail\ClickAndDrop\Rest\Api\LabelsApi

**Comment by Caffe1neAdd1ct** [comment]
@SithVicious can you try release tag v1.1 please?

**Comment by Caffe1neAdd1ct** [comment]
@SithVicious scrap that, can you try v1.3?

**Comment by Caffe1neAdd1ct** [comment]
Thanks for reporting, closing this issue for now feel free to raise another if this is still a problem.
