### ISSUE TITLE
Call to undefined method Brick\Math\BigDecimal::swaggerFormats()

### ISSUE THREAD

**Issue by miguelfspinto** [zVPS/royal-mail-click-drop-rest-api-client#4]
I'm having the following error:

![image](https://user-images.githubusercontent.com/4464216/138097523-ae6b3ea4-a695-4a9f-ade7-0fa27d32353b.png)

Can you help please?

**Comment by Caffe1neAdd1ct** [comment]
@miguelfspinto Any chance you can provide a little more information?

Which API call are you trying?
Can you provide example sample code?

**Comment by Caffe1neAdd1ct** [comment]
https://github.com/swagger-api/swagger-codegen/issues/9353

**Comment by Caffe1neAdd1ct** [comment]
I've recompiled and released v1.4, the model classes have moved to `Model` instead of `model` on the namespace now.

I'm also contacting Royal Mail to see if there is a sandbox or developer account i can register to test this package properly.

Let me know how you get on with v1.4 please.

**Comment by miguelfspinto** [comment]
please ignore the comment. the issue was solved.

**Comment by Caffe1neAdd1ct** [comment]
@miguelfspinto how did you resolve? I've made changes to the SDK to fix for you, did these fix the issue?

**Comment by miguelfspinto** [comment]
> @miguelfspinto how did you resolve? I've made changes to the SDK to fix for you, did these fix the issue?

Yes, it helped.

**Comment by Caffe1neAdd1ct** [comment]
Thanks for the update :) 

Any further issues just raise another issue :+1:
