### ISSUE TITLE
Manifest orders now available for OBA accounts user

### ISSUE THREAD

**Issue by sunil11475-dev** [zVPS/royal-mail-click-drop-rest-api-client#8]
@Caffe1neAdd1ct Hope you well.

Can you please update the code file and documentation because now Manifest orders available for OBA accounts users?

Thanks

**Comment by Caffe1neAdd1ct** [comment]
@sunil11475-dev happy to re-generate the API client, might be able to fit this in next week.

**Comment by sunil11475-dev** [comment]
@Caffe1neAdd1ct Thanks, I have manage to re-generate the files using click-and-drop-api-v1.yaml on swagger and added the Manifest files in to your project file but getting this error - 

Exception when calling ManifestsApi->createManifestsAsync: [500] Server error: POST https://api.parcel.royalmail.com/api/v1/manifests resulted in a 500 Internal Server Error response: {"code":"INTERNALSERVERERROR","message":"Can not process your request at the moment. Please contact support or try again later."}

Exception when calling ManifestsApi->getManifestsAsync: [500] Server error: GET https://api.parcel.royalmail.com/api/v1/manifests/08ed6597-d4b4-47e4-XXXX-0dea7a7XXX7a resulted in a 500 Internal Server Error response: {"code":"INTERNALSERVERERROR","message":"Can not process your request at the moment. Please contact support or try again later."}

It's server side error, I have made the enquiry with C&D support team, let see what they going say.
